/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Models.Atividade;
import Models.Materia;
import com.lowagie.text.pdf.AcroFields.Item;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author lukra
 */
public final class CadastrarAtividade extends javax.swing.JFrame {
    
    List<Atividade> atv;
    int prodAtual = 0;
    boolean atualizando = true;
    /**
     * Creates new form CadastrarAtividade
     */
    public CadastrarAtividade() {
        initComponents();
        carregaAtividade();
    }
    
    public void carregaAtividade() {
        try {
            atv = Atividade.buscarAtividade();
            preencheCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar Produtos!");
            this.dispose();
        }    
    }
    
    public void preencheCampos() {
        
        edtCodigo.setEnabled(false);
        
        if (atv.size() > 0) {
            edtCodigo.setText(String.valueOf(atv.get(prodAtual).getId()));
            jtAtividadeTitulo.setText(atv.get(prodAtual).getTitulo());
            jtAtividadeData.setText(String.valueOf(atv.get(prodAtual).getDate()));
            jtAtividaDescricao.setText(atv.get(prodAtual).getDescricao());
            
            if (prodAtual == 0) {
                jbAnterio.setEnabled(false);
            }
            else {
               jbAnterio.setEnabled(true);
            }

            if (prodAtual == atv.size() - 1) {
                jbProximo.setEnabled(false);
            }
            else {
                jbProximo.setEnabled(true);
            }
        }
        else {
            edtCodigo.setText("Automático...");
            jbAnterio.setEnabled(false);
            jbProximo.setEnabled(false);
            jbCadastrarAtividade.setEnabled(true);
            atualizando = false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtAtividadeTitulo = new javax.swing.JTextField();
        jtAtividaDescricao = new javax.swing.JTextField();
        jbCadastrarAtividade = new javax.swing.JButton();
        jbProximo = new javax.swing.JButton();
        jbAnterio = new javax.swing.JButton();
        edtCodigo = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbMateria = new javax.swing.JComboBox();
        jtAtividadeData = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Atividade");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Atividade"));

        jl.setText("Titulo");

        jLabel1.setText("Data");

        jLabel2.setText("Descrição ");

        jbCadastrarAtividade.setBackground(new java.awt.Color(255, 255, 51));
        jbCadastrarAtividade.setText("Cadastrar");
        jbCadastrarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarAtividadeActionPerformed(evt);
            }
        });

        jbProximo.setBackground(new java.awt.Color(255, 255, 51));
        jbProximo.setText(">>");
        jbProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProximoActionPerformed(evt);
            }
        });

        jbAnterio.setBackground(new java.awt.Color(255, 255, 51));
        jbAnterio.setText("<<");
        jbAnterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnterioActionPerformed(evt);
            }
        });

        edtCodigo.setEditable(false);

        jbNovo.setBackground(new java.awt.Color(255, 255, 51));
        jbNovo.setText("+");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jLabel3.setText("Matéria");

        cbMateria.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbMateriaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateriaActionPerformed(evt);
            }
        });

        jtAtividadeData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));

        jLabel4.setText("YYYY/MM/DD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAnterio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtAtividadeData, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtAtividaDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCadastrarAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtAtividadeTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbAnterio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(edtCodigo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtAtividadeTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtAtividadeData, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtAtividaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCadastrarAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jbNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarAtividadeActionPerformed
        String titulo = jtAtividadeTitulo.getText();
        String data = jtAtividadeData.getText();
        String descricao = jtAtividaDescricao.getText();
        int x = cbMateria.getSelectedIndex();
        //String petName = (String)a.getSelectedItem();
        Materia item = (Materia)cbMateria.getSelectedItem();
        
        if (titulo.length() == 0) {
            JOptionPane.showMessageDialog(this, "Você deve informar a Titulo!");
            return;
        }
        
        if (data.length() == 0) {
            JOptionPane.showMessageDialog(this, "Você deve informar a Data!");
            return;
        }
        
        if (descricao.length() == 0) {
            JOptionPane.showMessageDialog(this, "Você deve informar a Descrição!");
            return;
        }
        
        
        Atividade p = new Atividade();
        p.setTitulo(titulo);
        p.setDate(data);
        p.setDescricao(descricao);
        p.setMateria_id("" + item.getId());
        try {
            if (atualizando) {
                p.atualizarAtividade();
            }
            else {
                p.adicionarAtividade();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            return;
        }
        atualizando = true;
        carregaAtividade();
        
        JOptionPane.showMessageDialog(this, "Atividade salvo com sucesso!");
    }//GEN-LAST:event_jbCadastrarAtividadeActionPerformed

    private void jbProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProximoActionPerformed
        prodAtual++;
        preencheCampos();
    }//GEN-LAST:event_jbProximoActionPerformed

    private void jbAnterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnterioActionPerformed
        prodAtual--;
        preencheCampos();
    }//GEN-LAST:event_jbAnterioActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        edtCodigo.setText("Automático...");
        jtAtividadeTitulo.setText("");
        jtAtividadeData.setText("");
        jtAtividaDescricao.setText("");
        atualizando = false;
    }//GEN-LAST:event_jbNovoActionPerformed

    private void cbMateriaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbMateriaAncestorAdded
        Materia mat = new Materia();
        try {
            List<Materia> lisMat = Materia.buscarMateria();
            cbMateria.removeAll();
            
            //System.out.println(mat.getId());
            for(Materia f : lisMat){              
                
                cbMateria.addItem(f);
                
            }
            
        } catch (Exception ex) {
            Logger.getLogger(CadastrarAtividade.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_cbMateriaAncestorAdded

    private void cbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAtividade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbMateria;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAnterio;
    private javax.swing.JButton jbCadastrarAtividade;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbProximo;
    private javax.swing.JLabel jl;
    private javax.swing.JTextField jtAtividaDescricao;
    private javax.swing.JFormattedTextField jtAtividadeData;
    private javax.swing.JTextField jtAtividadeTitulo;
    // End of variables declaration//GEN-END:variables
}
