/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Models.Materia;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author lukra
 */
public class CadastrarMateria extends javax.swing.JFrame {
    List<Materia> mat;
    int prodAtual = 0;
    boolean atualizando = true;
    /**
     * Creates new form CadastrarMateria
     */
    public CadastrarMateria() {
        initComponents();
        carregarMateria();
    }
     public void carregarMateria() {
        try {
            mat = Materia.buscarMateria();
            preencheCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar Produtos!");
            this.dispose();
        }    
    }
    public void preencheCampos() {
        
        jtCodigo.setEnabled(false);
        
        if (mat.size() > 0) {
            jtCodigo.setText(String.valueOf(mat.get(prodAtual).getId()));
            jtMateriaNome.setText(mat.get(prodAtual).getNome());
            jtMateriaData.setText(String.valueOf(mat.get(prodAtual).getHorario()));
            jtMateriaDuracao.setText(mat.get(prodAtual).getDuracao() + "H");
            
            if (prodAtual == 0) {
                jbAnterio.setEnabled(false);
            }
            else {
                jbAnterio.setEnabled(true);
            }

            if (prodAtual == mat.size() - 1) {
                jbProximo.setEnabled(false);
            }
            else {
                jbProximo.setEnabled(true);
            }
        }
        else {
            jtCodigo.setText("Automático...");
            jbAnterio.setEnabled(false);
            jbProximo.setEnabled(false);
            jbCadastrarMateria.setEnabled(true);
            atualizando = false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCadastrarMateria = new javax.swing.JButton();
        jbProximo = new javax.swing.JButton();
        jbAnterio = new javax.swing.JButton();
        jl = new javax.swing.JLabel();
        Horario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtMateriaNome = new javax.swing.JTextField();
        jtMateriaData = new javax.swing.JTextField();
        jtMateriaDuracao = new javax.swing.JTextField();
        jbNovo = new javax.swing.JButton();
        jtCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Matéria");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Matéria"));

        jbCadastrarMateria.setBackground(new java.awt.Color(51, 51, 255));
        jbCadastrarMateria.setText("Cadastrar");
        jbCadastrarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarMateriaActionPerformed(evt);
            }
        });

        jbProximo.setBackground(new java.awt.Color(51, 51, 255));
        jbProximo.setText(">>");
        jbProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProximoActionPerformed(evt);
            }
        });

        jbAnterio.setBackground(new java.awt.Color(51, 51, 255));
        jbAnterio.setText("<<");
        jbAnterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnterioActionPerformed(evt);
            }
        });

        jl.setText("Titulo");

        Horario.setText("Horário");

        jLabel2.setText("Duração");

        jbNovo.setBackground(new java.awt.Color(51, 51, 255));
        jbNovo.setText("+");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jtCodigo.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                        .addComponent(jbAnterio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtMateriaDuracao)
                            .addComponent(jtMateriaNome)
                            .addComponent(jtMateriaData)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl)
                                    .addComponent(Horario)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCadastrarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbAnterio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtMateriaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Horario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtMateriaData, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtMateriaDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jbCadastrarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarMateriaActionPerformed
        String nome = jtMateriaNome.getText();
        String data = jtMateriaData.getText();
        String duracao = jtMateriaDuracao.getText();
        
        if (nome.length() == 0) {
            JOptionPane.showMessageDialog(this, "Você deve informar a Nome!");
            return;
        }
        
        if (data.length() == 0) {
            JOptionPane.showMessageDialog(this, "Você deve informar a Data!");
            return;
        }
        
        if (duracao.length() == 0) {
            JOptionPane.showMessageDialog(this, "Você deve informar a Duração!");
            return;
        }
        
        
        Materia p = new Materia();
        p.setNome(nome);
        p.setHorario(data);
        p.setDuracao(duracao);
                
        try {
            if (atualizando) {
                p.atualizarMateria();
            }
            else {
                p.adicionarMateria();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            return;
        }
        atualizando = true;
        carregarMateria();
        
        JOptionPane.showMessageDialog(this, "Materia salva com sucesso!");
    }//GEN-LAST:event_jbCadastrarMateriaActionPerformed

    private void jbProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProximoActionPerformed
       prodAtual++;
       preencheCampos();
    }//GEN-LAST:event_jbProximoActionPerformed

    private void jbAnterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnterioActionPerformed
        prodAtual--;
        preencheCampos();
    }//GEN-LAST:event_jbAnterioActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jtCodigo.setText("Automático...");
        jtMateriaNome.setText("");
        jtMateriaData.setText("");
        jtMateriaDuracao.setText("");
        atualizando = false;
    }//GEN-LAST:event_jbNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarMateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Horario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAnterio;
    private javax.swing.JButton jbCadastrarMateria;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbProximo;
    private javax.swing.JLabel jl;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtMateriaData;
    private javax.swing.JTextField jtMateriaDuracao;
    private javax.swing.JTextField jtMateriaNome;
    // End of variables declaration//GEN-END:variables
}
