/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Models.Aluno;
import Models.materiaHasAluno;
import Models.Materia;
import Models.Professor;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lukra
 */
public class CadastrarAluno extends javax.swing.JFrame {
    List<Aluno> alun;
    int aluAtual = 0;
    boolean atualizando = true;
    List<Materia> mat;
    
    int idAlun;
    /**
     * Creates new form CadastrarUsuario
     */
    public CadastrarAluno() throws Exception {
        initComponents();
        carregarAluno();
        DefaultTableModel model = (DefaultTableModel) tbDados.getModel();
        tbDados.setRowSorter(new TableRowSorter(model));
        listarDadosMateria();
        
    }
    public void carregarAluno() {
        try {
            alun = Aluno.buscarAluno();
            preencheCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar Produtos!");
            this.dispose();
        }    
    }
    
    public void preencheCampos() {
        
        jtCodigo.setEnabled(false);
        
        if (alun.size() > 0) {
            jtCodigo.setText(String.valueOf(alun.get(aluAtual).getId()));
            jtNomeAluno.setText(alun.get(aluAtual).getNome());
            jtEmailAluno.setText(String.valueOf(alun.get(aluAtual).getEmail()));
            jtImagemAluno.setText(alun.get(aluAtual).getImagem());
            idAlun = alun.get(aluAtual).getId();
            if (aluAtual == 0) {
                jbAnterior.setEnabled(false);
            }
            else {
                jbAnterior.setEnabled(true);
            }

            if (aluAtual == alun.size() - 1) {
                jbProximo.setEnabled(false);
            }
            else {
                jbProximo.setEnabled(true);
            }
        }
        else {
            jtCodigo.setText("Automático...");
            jbAnterior.setEnabled(false);
            jbProximo.setEnabled(false);
            jbSelecionar.setEnabled(true);
            atualizando = false;
        }
    }
    
   
    
    public void listarDadosMateria() throws Exception{
        mat = Materia.buscarMateria();
        //boolean funfa = false;
        DefaultTableModel model = (DefaultTableModel) tbDados.getModel();
       
        model.setNumRows(0);
        for(Materia m : mat){
            
            model.addRow(new Object[]{               
                false,
                m.getId(),
                m.getNome()            
            });
            //System.out.println();
            //if( == true){
              //  a = m.getId();
               // b = 1;
               // mha.setIdAluno(b);
                //mha.setIdMateria(a);
               // mha.adicionarMateriaHasAluno();
            //}
            //funfa = false;
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbProximo = new javax.swing.JButton();
        jbAnterior = new javax.swing.JButton();
        jtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtNomeAluno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtEmailAluno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbSelecionar = new javax.swing.JButton();
        jtImagemAluno = new javax.swing.JTextField();
        jbCadastrarAluno = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDados = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Aluno");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Aluno"));

        jbProximo.setBackground(new java.awt.Color(102, 255, 102));
        jbProximo.setText(">>");
        jbProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProximoActionPerformed(evt);
            }
        });

        jbAnterior.setBackground(new java.awt.Color(102, 255, 102));
        jbAnterior.setText("<<");
        jbAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnteriorActionPerformed(evt);
            }
        });

        jtCodigo.setEditable(false);

        jLabel2.setText("Nome");

        jLabel3.setText("Email");

        jLabel4.setText("Imagem");

        jbSelecionar.setBackground(new java.awt.Color(102, 255, 102));
        jbSelecionar.setText("Selecionar");
        jbSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelecionarActionPerformed(evt);
            }
        });

        jtImagemAluno.setEditable(false);

        jbCadastrarAluno.setBackground(new java.awt.Color(102, 255, 102));
        jbCadastrarAluno.setText("Cadastrar");
        jbCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarAlunoActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Selecionar", "Id da Matéria ", "Nome da Matéria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbDados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtEmailAluno)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                        .addComponent(jbAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtNomeAluno)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtImagemAluno))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jbProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtEmailAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtImagemAluno)
                    .addComponent(jbSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCadastrarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelecionarActionPerformed
       int ret = jFileChooser1.showOpenDialog(this);
        if (ret == JFileChooser.APPROVE_OPTION) {
            File img = jFileChooser1.getSelectedFile();
            jtImagemAluno.setText(img.getAbsolutePath());
        }
    }//GEN-LAST:event_jbSelecionarActionPerformed

    private void jbCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarAlunoActionPerformed
        String nome = jtNomeAluno.getText();       
        String email = jtEmailAluno.getText();      
        String img = jtImagemAluno.getText();
        String res = img.replaceAll("\\\\","/");
        
        
        if (nome.length() == 0) {
            JOptionPane.showMessageDialog(this, "Você deve informar o Nome!");
            return;
        }
        
                
        if (email.equals("Selecione...")) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar um Email!");
            return;
        }
        
        if (img.equals("Selecione...")) {
            JOptionPane.showMessageDialog(this, "Você deve selecionar uma Imagem!");
            return;
        }
        
        Aluno p = new Aluno();
                p.setNome(nome);               
                p.setEmail(email);                
                p.setImagem(res); 
                
        for(int linha=0; linha<tbDados.getRowCount();linha++){
            boolean valorColuna=(boolean)tbDados.getModel().getValueAt(linha,0); 
            System.out.println(valorColuna);
            try {
                
                if(valorColuna == true){   
                    materiaHasAluno mha = new materiaHasAluno();
                    String a = "" + tbDados.getModel().getValueAt(linha, 1);                
                    mha.setIdAluno("" + idAlun);  
                    mha.setIdMateria(a);
                                      
                    mha.adicionarMateriaHasAluno();

                }
            
            } catch (Exception ex) {
                Logger.getLogger(CadastrarAluno.class.getName()).log(Level.SEVERE, null, ex);
            }
        }      
        try {
            if (atualizando) {
                p.atualizarAluno();
               
            }
            else {
                p.adicionarAluno();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            return;
        }
        atualizando = true;
        carregarAluno();
        try {
            listarDadosMateria();
        } catch (Exception ex) {
            Logger.getLogger(CadastrarAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Aluno salvo com sucesso!");
    }//GEN-LAST:event_jbCadastrarAlunoActionPerformed

    private void jbAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnteriorActionPerformed
       aluAtual--;
       preencheCampos();
        try {
            listarDadosMateria();
        } catch (Exception ex) {
            Logger.getLogger(CadastrarAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbAnteriorActionPerformed

    private void jbProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProximoActionPerformed
       aluAtual++;
       preencheCampos();
        try {
            listarDadosMateria();
        } catch (Exception ex) {
            Logger.getLogger(CadastrarAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbProximoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jtNomeAluno.setText("");       
        jtEmailAluno.setText("");      
        jtImagemAluno.setText("");
        jtCodigo.setText("auto");
        atualizando  = false;
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 try {                 
                    new CadastrarAluno().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(CadastrarAluno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAnterior;
    private javax.swing.JButton jbCadastrarAluno;
    private javax.swing.JButton jbProximo;
    private javax.swing.JButton jbSelecionar;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtEmailAluno;
    private javax.swing.JTextField jtImagemAluno;
    private javax.swing.JTextField jtNomeAluno;
    private javax.swing.JTable tbDados;
    // End of variables declaration//GEN-END:variables
}
